version: "3.9"

services:
  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: ai_service
    ports:
      - "5001:5000"
    volumes:
      - ./ai_service:/app
    environment:
      - PYTHONUNBUFFERED=1

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5002:5000"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1

  landing:
    build:
      context: ./landing
      dockerfile: Dockerfile
    container_name: landing
    ports:
      - "3000:3000"
    volumes:
      - ./landing:/app
    environment:
      - NODE_ENV=development
